// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockContainer is an autogenerated mock type for the Container type
type MockContainer struct {
	mock.Mock
}

type MockContainer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContainer) EXPECT() *MockContainer_Expecter {
	return &MockContainer_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: name
func (_m *MockContainer) Get(name string) (any, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 any
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (any, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) any); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContainer_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockContainer_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - name string
func (_e *MockContainer_Expecter) Get(name interface{}) *MockContainer_Get_Call {
	return &MockContainer_Get_Call{Call: _e.mock.On("Get", name)}
}

func (_c *MockContainer_Get_Call) Run(run func(name string)) *MockContainer_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockContainer_Get_Call) Return(_a0 any, _a1 error) *MockContainer_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContainer_Get_Call) RunAndReturn(run func(string) (any, error)) *MockContainer_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockContainer creates a new instance of MockContainer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContainer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContainer {
	mock := &MockContainer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
